services:
  - type: web
    name: xray-prediction-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers=4 --threads=2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PIP_EXTRA_INDEX_URL
        value: https://download.pytorch.org/whl/cpu
    healthCheckPath: /health
    healthCheckTimeout: 100
    healthCheckInterval: 15
    autoDeploy: true
    pullRequestPreviewsEnabled: false